version: '3.8'

services:

  symfony:
    build: ./docker/symfony
    container_name: symfony
    ports:
      - "8245:80"
    volumes:
      - ./docker/symfony/vhosts:/etc/apache2/sites-enabled
      - ./symfony:/var/www/symfony
    restart: always
    networks:
      - dev

#  maildev:
#    image: maildev/maildev
#    container_name: maildev
#    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
#    ports:
#      - "8081:80"
#    restart: always
#    networks:
#      - dev

  mariadb:
    image: mariadb:10.9.3
    container_name: mariadb
    ports: [ "3306:3306" ]
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: pma
    restart: always
    depends_on:
      - mariadb
    ports: [ "8080:80" ]
    environment:
      PMA_HOST: mariadb
    networks:
      - dev

  caddy:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: mercure
    environment:
      # Uncomment the following line to disable HTTPS
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES:
        cors_origins "http://localhost:3000"
        cors_origins "http://localhost:8245"
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dev

networks:
  dev:

volumes:
  db_data: