<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYtVbzwp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYtVbzwp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYtVbzwp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYtVbzwp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYtVbzwp\App_KernelDevDebugContainer([
    'container.build_hash' => 'YtVbzwp',
    'container.build_id' => '7e4c36f1',
    'container.build_time' => 1670364304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYtVbzwp');
